In [3]:
import os
from sklearn import datasets
import sklearn.datasets
import sklearn.ensemble
import numpy as np

In [5]:
iris = sklearn.datasets.load_iris()

In [6]:
X = iris.data
Y = iris.target

In [7]:
X.shape

(150, 4)

In [8]:
Y.shape

(150,)

In [11]:
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler(feature_range = (0,1))
minmax_scaler.fit(X)

MinMaxScaler()

In [12]:
X = minmax_scaler.transform(X)

In [13]:
X

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [14]:
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(X, Y, train_size=0.90)

In [15]:
train.shape

(135, 4)

In [16]:
test.shape

(15, 4)

In [17]:
labels_train

array([2, 0, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 1, 2, 0,
       1, 0, 0, 0, 2, 0, 0, 2, 1, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 0,
       2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 2, 1, 1, 2, 0, 1, 1,
       2, 2, 0, 2, 1, 2, 2, 1, 0, 1, 2, 1, 0, 0, 0, 2, 0, 1, 2, 1, 1, 0,
       2, 1, 2, 0, 0, 1, 0, 1, 2, 2, 0, 0, 1, 1, 2, 0, 2, 0, 2, 0, 0, 2,
       2, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 0, 2, 1, 2, 0, 1, 2, 0, 2, 0, 2,
       1, 2, 1])

In [18]:
labels_test

array([2, 1, 2, 2, 1, 1, 1, 0, 2, 1, 1, 0, 1, 2, 2])

In [19]:
D = np.c_[train, labels_train]

In [20]:
os.chdir('C:/Users/walke/Docker_Practice/GL_model_deplyment')

In [21]:
np.savetxt('iris_train.csv', D, delimiter=",")

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import linear_model
import pandas as pd

In [25]:
chunksize = 25

for chunk in pd.read_csv('iris_train.csv', header=None, chunksize= chunksize):
    train_sub=chunk
    print(train_sub)
    Y = train_sub[4]
    X = train_sub.drop([4],axis=1)
    
    clf = linear_model.SGDClassifier()
    clf.partial_fit(X,Y,classes=np.unique(Y))
    print(clf.coef_)
    clf.predict(test)
    pred=clf.predict(test)
    print(pred)
    print(accuracy_score(pred, labels_test))

           0         1         2         3    4
0   0.916667  0.416667  0.949153  0.833333  2.0
1   0.416667  0.833333  0.033898  0.041667  0.0
2   0.416667  0.333333  0.694915  0.958333  2.0
3   0.333333  0.250000  0.576271  0.458333  1.0
4   0.416667  0.291667  0.525424  0.375000  1.0
5   0.194444  0.625000  0.050847  0.083333  0.0
6   0.222222  0.208333  0.338983  0.416667  1.0
7   0.444444  0.500000  0.644068  0.708333  1.0
8   0.166667  0.458333  0.084746  0.000000  0.0
9   0.277778  0.708333  0.084746  0.041667  0.0
10  0.777778  0.416667  0.830508  0.833333  2.0
11  0.805556  0.416667  0.813559  0.625000  2.0
12  0.194444  0.500000  0.033898  0.041667  0.0
13  0.555556  0.208333  0.661017  0.583333  1.0
14  0.361111  0.416667  0.525424  0.500000  1.0
15  0.638889  0.416667  0.576271  0.541667  1.0
16  0.555556  0.291667  0.661017  0.708333  2.0
17  0.833333  0.375000  0.898305  0.708333  2.0
18  0.583333  0.291667  0.728814  0.750000  2.0
19  0.333333  0.125000  0.508475  0.5000